#!/usr/bin/python3
# Name: bitly
# Purpose: this is a sample XCloud service plugin which shortens a URL
#          using the bit.ly API
# Usage: bitly URL
# 
# Licence: MIT License
# Copyright (c) 2021 Mark Brooker
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import requests
import json
import sys

headers = { "Authorization": "Bearer YOUR_API_KEY_HERE",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0" }

data = json.dumps({ "long_url": sys.argv[1], "domain": "bit.ly" })

response = requests.post("https://api-ssl.bitly.com/v4/shorten", headers=headers, data=data)

if response.ok:
    print(response.json()["link"], end="")
else:
    print(f"rc {response.status_code}", end="")
